### PR TITLE
https://github.com/garga3838

### PR DESCRIPTION
**Pull request by garga3838**
https://github.com/PGPAuth/PGPAuth_Android.git

### CODE REVIEW

**Comment by garga3838** [comment]
repository-open-graph-template

**Comment by garga3838** [comment]
[](url)

**Comment by garga3838** [comment]
cb430207fce90873c536eaa6da8deb0d8b19166f

**Comment by LittleFox94** [comment]
This whole thing looks like spam :/

Reopen with a proper comment if misjudged

**Pull request closed without merging**
